# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [main]
    paths:
      - '*.ts'
      - '*.js'
      - '*.json'
      - '*.yaml'
      - '.github/**/test.yml'
      - 'src/**/*'
      - 'tests/**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ~1.x

      - name: Tests
        run: deno task test

      - name: Benchmark
        run: deno task bench
